version: '3'
services:
  database:
    image: "debezium/postgres" 
    restart: always
    container_name: postgres

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./sql/01.create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/02.fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
volumes:
  database-data: 

