version: '3'
services:

  database:
    #image: container-registry.oracle.com/database/enterprise:12.2.0.1-slim
    #image: container-registry.oracle.com/database/standard:12.1.0.2
          image: oracle/database:12.2.0.1-ee
    container_name: oracle12c
    restart: always
    shm_size: 4gb
    volumes:
      - oracle-data:/ORCL
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      - DB_SID=ORCL
      - DB_PDB=PDB1
      - DB_MEMORY=4gb
      - DB_PWD=oracle
      - ORACLE_SID=ORCL
      - ORACLE_PDB=PDB1
      - ORACLE_PWD=oracle
      - ORACLE_EDITION=standard
      - ORACLE_CHARACTERSET=AL32UTF8
      - ENABLE_ARCHIVELOG=true
      #- TNS_ADMIN=/u01/app/oracle/product/12.1.0/dbhome_1/network/admin
    networks:
      - oracle-network

networks:
  oracle-network:

volumes:
  oracle-data:      
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/oracle-data
      o: bind
